version: '3.8'

services:
  ionic-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app       # Monte le projet pour le développement en live
      - /app/node_modules # Pour éviter de remplacer node_modules du conteneur
    ports:
      - "8100:8100"  # Expose le serveur de dev Ionic
    stdin_open: true
    tty: true
